language: 
 - node_js

node_js:
 - '7'
 - '9'

install:
 - yarn install
 - yarn install --only=dev
 - npm install codecov nyc -g

script:
 - nyc mocha

after_success:
 - codecov -f ./coverage/coverage-final.json
