/**
 * @overview generated by ghoti-cli
 * @fileoverview Config
 */

export default {
    isDebug: true,
    backgroundColor: 'white',
    devURL: 'http://localhost:8080',
    prodURL: `file://${__dirname}/../renderer/index.html`,
};
